In [ ]:
# DATA WRANGLING
# Reading CSV file and adding 2 columns to create a new column
    import pandas
    baseball_data = pandas.read_csv('Master.csv')
    print baseball_data
    baseball_data['height_plus_weight'] = baseball_data['height'] + baseball_data['weight']
    baseball_data.to_csv('baseball_data_height_plus_weight.csv')
    
    def add_full_name(path_to_csv, path_to_new_csv):
        dataframe = pandas.read_csv(path_to_csv)
        dataframe['name_full'] = dataframe['nameFirst'] + ' ' + data['nameLast']
        dataframe.to_csv(path_to_new_csv)
    
# Simple Queries
    SELECT *  # produces all rows and columns
    FROM aadhaar_data  
    LIMIT 20 # limits to first 20 rows

# Read in our aadhaar_data csv to a pandas dataframe.  Afterwards, we rename the columns
# by replacing spaces with underscores and setting all characters to lowercase, so the
# column names more closely resemble columns names one might find in a table.
    
    def select_first_50(filename):
        aadhaar_data = pandas.read_csv(filename)
    aadhaar_data.rename(columns = lambda x: x.replace(' ', '_').lower(), inplace=True)
    
    # Select out the first 50 values for "registrar" and "enrolment_agency" 
    # in the aadhaar_data table using SQL syntax
    q = """ 
    SELECT 
    registrar, enrolment_agency
    FROM
    aadhar_data
    LIMIT 50;
    """
    #Execute your SQL command against the pandas frame
    aadhaar_solution = pandasql.sqldf(q.lower(), locals())
    return aadhaar_solution    

# Complex Queries
    SELECT * FROM aadhaar_data
    GROUP BY district 
    ORDER BY id   # allow you to sort by date
    ORDER BY id DESC   # descending order
    ORDER BY account_id, total_amt_usd DESC   # sorting occurs using left most column  first and next column from the left  and so on
    WHERE state='Gujarat'  # allows you to filter set of results based on specific criteria (> < >= <= = != LIKE IN NOT OR AND BETWEEN)

# Write a query that will select from the aadhaar_data table how many men and how 
# many women over the age of 50 have had aadhaar generated for them in each district.
     q = """
    SELECT district, Sum(aadhaar_generated)
    FROM aadhaar_data WHERE age>50 
    GROUP BY gender, district;
    """

# ACCESING API EFFICIENTLY
    if _name_=='_main_':
    url = 'http://ws.audioscrabbles.com/2.0/?method=album.getinfo&api_key=[API_KEY]&artist=Rihanna&album=Loud&format=json'
    data = requests.get(url).text
    data = json.loads(data)
    print data
    print data['topartists']['artists'][O]['name']

    
# Impute using Linear Regression

# fillna(value) passes single value to replace NAs in a dataframe or series
    dataframe['column'] = dataframe['column'].fillna(value)
    
# Linear Regression replaces mean value for NAs
    baseball['weight'] = baseball['weight'].fillna(numpy.mean(baseball['weight']))
    print numpy.sum(baseball['weight']), numpy.mean(baseball['weight'])